[package]
name = "atlas-python"
version = "0.11.0"
edition = "2021"

[lib]
name = "_atlas"
crate-type = ["cdylib", "rlib"]

[dependencies]
atlas = { package = "atlas-rust", path = ".." }
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py310"] }
numpy = "0.28"
ndarray = "0.17"
object_store = "0.13"
pyo3-object_store = "0.9"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
